export { SalesComponent } from './sales.component';
export { SalesInvoiceComponent } from './sales-invoice/sales-invoice.component';
export { SalesReturnComponent } from './sales-return/sales-return.component';
export { CreateBillComponent } from './sales-invoice/create-bill/create-bill.component';
export { SalesReturnViewComponent } from './sales-return/sales-return-view/sales-return-view.component';
export { StocktransferComponent } from './stocktransfer/stocktransfer.component';
export { CreateStockTransferComponent } from './stocktransfer/create-stock-transfer/create-stock-transfer.component';
export { PurchaseComponent } from './purchase/purchase.component';
export { PurchaseCreateComponent } from './purchase/purchase-create/purchase-create.component';