export {GeneralledgerComponent} from './generalledger.component';
export {AccountsGroupComponent} from './accountsgroup/accountsgroup.component';
export {SubGroupComponent} from './subgroup/subgroup.component';
export {UndersubGroupComponent} from './undersubgroup/undersubgroup.component';
export {GlAccountsComponent} from './glaccounts/glaccounts.component';
export {GlSubcodeComponent } from './glsubcode/glsubcode.component';
export {TaxIntegrationComponent } from './taxintegration/taxintegration.component';
export {CashAccToBranchesComponent } from './cashacctobranches/cashacctobranches.component';
export {AccToAccClassComponent } from './acctoaccclass/acctoaccclass.component';
export {VoucherTypesComponent} from './vouchertypes/vouchertypes.component';
